name: qiskit-surface-code-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - notebook
  - jupyter
  - pip:
    - qiskit
    - pylatexenc
    - retworkx
